Updated API links in guides - phase 4
ember-learn/guides-source pull request #1602
Opened 2020-11-02 23:20 UTC by neojp

This PR addresses #1440 for Ember `v2.17.0` and `v3.0.0`.

## Process

1. Ran the script `npm run release:guides:links <guides-path> <version>`
2. Manually checked updated links
3. Ran `npm run test:node-local` to check all external links automatically

2020-11-03 16:45 UTC, ijlee2 commented
I rebased the branch so that the pull request will be checked against GitHub Actions instead of Travis.

2020-11-04 22:02 UTC, ijlee2 commented on guides/v2.17.0/models/customizing-adapters.md
> +[volatile](https://api.emberjs.com/ember/2.17/classes/@ember%2Fobject%2Fcomputed/methods/property?anchor=volatile&show=inherited%2Cprotected%2Cprivate%2Cdeprecated)
```suggestion
[volatile](https://api.emberjs.com/ember/2.17/classes/@ember%2Fobject%2Fcomputed/methods/property?anchor=volatile)
```

2020-11-04 22:03 UTC, ijlee2 commented on guides/v2.17.0/models/customizing-serializers.md
> +[`normalizeResponse()`](https://api.emberjs.com/ember-data/2.17/classes/DS.JSONAPISerializer/methods/serialize?anchor=normalizeResponse)
```suggestion
[`normalizeResponse()`](https://api.emberjs.com/ember-data/2.17/classes/DS.JSONAPISerializer/methods/normalizeResponse?anchor=normalizeResponse)
```

2020-11-04 22:03 UTC, ijlee2 commented on guides/v2.17.0/models/customizing-serializers.md
> +[`normalize()`](https://api.emberjs.com/ember-data/2.17/classes/DS.JSONAPISerializer/methods/serialize?anchor=normalize)
```suggestion
[`normalize()`](https://api.emberjs.com/ember-data/2.17/classes/DS.JSONAPISerializer/methods/normalize?anchor=normalize)
```

2020-11-04 22:04 UTC, ijlee2 commented on guides/v2.17.0/models/customizing-serializers.md
> +[`keyForRelationship()`](https://api.emberjs.com/ember-data/2.17/classes/DS.JSONAPISerializer/methods/keyForAttribute?anchor=keyForRelationship)
```suggestion
[`keyForRelationship()`](https://api.emberjs.com/ember-data/2.17/classes/DS.JSONAPISerializer/methods/keyForRelationship?anchor=keyForRelationship)
```

2020-11-04 22:05 UTC, ijlee2 commented on guides/v2.17.0/models/finding-records.md
> +Use [`store.peekRecord()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/findRecord?anchor=peekRecord) to retrieve a record by its type and ID, without making a network request.
```suggestion
Use [`store.peekRecord()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/peekRecord?anchor=peekRecord) to retrieve a record by its type and ID, without making a network request.
```

2020-11-04 22:05 UTC, ijlee2 commented on guides/v2.17.0/models/finding-records.md
> +Ember Data provides a convenience method [`store.queryRecord()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/query?anchor=queryRecord)that will return a promise that resolves wit
```suggestion
Ember Data provides a convenience method [`store.queryRecord()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/queryRecord?anchor=queryRecord) that will return a promise that resolves with that single record.
```

2020-11-04 22:06 UTC, ijlee2 commented on guides/v2.17.0/models/finding-records.md
> +then calling [`store.queryRecord()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/query?anchor=queryRecord) will retrieve that object from the server:
```suggestion
then calling [`store.queryRecord()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/queryRecord?anchor=queryRecord) will retrieve that object from the server:
```

2020-11-04 22:06 UTC, ijlee2 commented on guides/v2.17.0/models/pushing-records-into-the-store.md
> +[`store.pushPayload()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/push?anchor=pushPayload) method.
```suggestion
[`store.pushPayload()`](https://api.emberjs.com/ember-data/2.17/classes/DS.Store/methods/pushPayload?anchor=pushPayload) method.
```

2020-11-04 22:08 UTC, ijlee2 requested changes
I visited all links in the first 15 files. Before I check the rest, can you fix all the occurrences of `bar?anchor=foo` (i.e. `foo` and `bar` don't match) in 2.17 and 3.0?

If you can make 1 or 2 commits, instead of applying the suggestion (which would trigger the CI to run multiple times), that'd be good.

2020-11-19 15:23 UTC, jenweber commented
@neojp do you have some time to apply these updates? We'd love to get this merged in. Thank you!

2020-11-21 03:45 UTC, neojp commented
I will work on this during the weekend. Thanks for the reminder!

2020-12-01 18:32 UTC, locks commented
Poke poke 😁

2020-12-03 13:29 UTC, neojp commented
@ijlee2 I've merged your changes suggestions into a single commit. Sorry for the delay, it's been a long month!

2020-12-03 13:36 UTC, ijlee2 commented
@neojp No worries. I hope you are well and appreciate your taking time to work on this issue!

2020-12-03 13:37 UTC, ijlee2 approved these changes
🎉

2020-12-03 13:40 UTC, merged