include new lang flag guidance issue #1599
ember-learn/guides-source pull request #1606
Opened 2020-11-04 21:45 UTC by fozy81

2020-11-04 21:54 UTC, fozy81 commented
Hi @locks - first draft for including `--lang` guidance. Please review, feedback welcome.

2020-12-01 18:31 UTC, locks requested changes
Small tweak inline. What do you think?

2020-12-01 18:31 UTC, locks commented on guides/release/accessibility/application-considerations.md
> +The `--lang` option on the `ember new` command sets the language for a new application.
```suggestion
A primary language should be defined on the `<html>` element's `lang` attribute. For new apps, you can use the `--lang` option on the `ember new` command to set the language for a new application.
```

2020-12-01 19:24 UTC, fozy81 commented
@locks Agree, that flows better. Thanks for your suggestion.

2020-12-01 19:35 UTC, locks approved these changes
Let's go!

2020-12-01 19:35 UTC, locks commented
Thanks for the help :) I'm waiting on CI to then merge your work.

2020-12-03 13:46 UTC, ijlee2 approved these changes
Thank you for adding an explanation of how to create an app with `lang` set up!

It seems that CI didn't work properly last time. I reran CI and think we can ignore the 2 jobs (`CI / Test app` and `CI / Test node-tests`) that had failed.

2020-12-03 13:46 UTC, merged