Add missing alt to example
ember-learn/guides-source pull request #1623
Opened 2020-12-30 08:11 UTC by srsgores

This adds the missing `alt` attribute (needed for screen readers and accessibility).

2020-12-30 14:16 UTC, ijlee2 requested changes
Hi, @srsgores. Thanks for noticing that the `<img>` element in the example is missing its `alt` attribute.

In this example, it looked to me like the `blog-logo` image is [decorative](https://www.w3.org/WAI/tutorials/images/decorative/). I believe, in such case, we will want to set an empty `alt` and a `role` of `presentation` instead:

```handlebars
<img src="./blog-logo.png" alt="" role="presentation">
```

What do you think about setting the `alt` to empty string? If this looks right to you, can we change line 274 as well as line 291 in the `block-content.md` file?

2021-01-27 20:57 UTC, ijlee2 commented
@srsgores Hello. I hope that this message finds you well. 👋

I was wondering if you can help complete the pull request. Once we add the empty alternate text to lines 274 and 291, I think we're good to go!

2021-01-27 21:06 UTC, srsgores reviewed
Should look better now

2021-02-27 08:25 UTC, ijlee2 approved these changes

2021-02-27 08:39 UTC, merged