Fix meta image
ember-learn/guides-source pull request #1647
Opened 2021-03-20 20:34 UTC by amyrlam

Resolves: https://github.com/ember-learn/guides-source/issues/1621

Related to: https://github.com/ember-learn/ember-website/pull/804

2021-03-20 20:35 UTC, amyrlam commented
I copied the contents from https://github.com/ember-learn/ember-website/pull/804/files except for ` <meta name="google-site-verification"` as wasn't sure what that was yet.

2021-03-22 06:55 UTC, ijlee2 requested changes
@amyrlam Thanks for working on a solution. I checked that the image shows up when I post a Guides link in a tweet.

Before we merge the pull request, I'd like to see application tests added so that there's no regression in the future. Can we update the file `https://github.com/ember-learn/guides-source/blob/master/tests/acceptance/meta-data-test.js` in the following manner:

```javascript
test('We set title and description correctly', async function(assert) {
  // Navigate to Routing, Defining Your Routes

  // Check title and description

  // Navigate to Services, Overview

  // Check title and description
});

test('We set metadata for Open Graph correctly', async function(assert) {
  // Navigate to Routing, Defining Your Routes

  // Check title, description, and image

  // Navigate to Services, Overview

  // Check title, description, and image
});

test('We set metadata for Twitter correctly', async function(assert) {
  // Navigate to Routing, Defining Your Routes

  // Check title, description, and image

  // Navigate to Services, Overview

  // Check title, description, and image
});
```

2021-03-25 17:58 UTC, locks commented on app/index.html
> +    <meta name="description" content="Ember.js helps developers be more productive out of the box. Designed with developer ergonomics in mind, its friendly APIs help you get your job done—fast.">
This is applied by guidemaker so it shouldn't be hardcoded in here.

2021-03-25 18:04 UTC, amyrlam commented
From the Learning Team meeting: This tests should be made in guidemaker, I just made a separate issue: https://github.com/empress/guidemaker/issues/51

2021-03-25 18:04 UTC, locks commented
We reviewed this at the learning meeting and decided to move the PR forward after removing the description since it is applied by guidemaker.
There are tests in guidemaker and empress for meta tags so we felt like upstreaming to those projects made more sense than adding the tests here.
We will follow with further upstream work.

2021-03-25 18:07 UTC, locks approved these changes

2021-03-25 18:07 UTC, merged