Add default block content example at the top of the section
ember-learn/guides-source pull request #1663
Opened 2021-03-29 17:37 UTC by barelyknown

I added a simple example, but did so in a way that acknowledges named blocks and the "default" block. I think that named blocks are a valuable feature, and acknowledging the little bit of complexity can make it all seem a little less magical when the reader encounters named blocks later.

2021-03-29 18:42 UTC, jaredgalanis approved these changes
Looks great! Thank you for contributing during the workshop!

2021-03-29 18:54 UTC, hergaiety approved these changes

2021-03-29 18:55 UTC, locks requested changes
I'll fill this out post-workshop :)

2021-04-01 23:19 UTC, jenweber commented
Hi @locks, just following up, what are the changes you are requesting?

Thanks @barelyknown for the PR!

2021-04-03 15:00 UTC, locks requested changes
Left some suggestions and comments. Thanks for kicking this off!

2021-04-03 15:02 UTC, locks commented
Note that I forgot: as per learning team decision, named block documentation should only be merged after 3.26 is released.

2021-04-18 13:59 UTC, barelyknown commented on guides/release/components/block-content.md
> +Block content can be both an easier and prettier way to provide a
Yeah, I see that. I just removed it.

2021-05-07 23:23 UTC, locks approved these changes

2021-05-07 23:24 UTC, merged

2021-05-07 23:25 UTC, locks commented
Thanks for the follow through @barelyknown!