Update customizing-adapters.md
ember-learn/guides-source pull request #1673
Opened 2021-04-03 00:22 UTC by esquith

2021-04-03 08:01 UTC, ijlee2 commented on guides/release/models/customizing-adapters.md
> +export default class PostAdapter extends JSONAPIAdapter {
**suggestion (blocking)**

The preceding paragraph, although not entirely clear, mentions overriding the default `application` adapter. As an example, I think the code showed overriding `namespace` with `api/v1`, which refers to an older version of someone's API.

```suggestion
export default class PostAdapter extends JSONAPIAdapter {
  namespace = 'api/v1';
```

2021-04-03 08:09 UTC, ijlee2 commented on guides/release/models/customizing-adapters.md
> +export default class PostAdapter extends JSONAPIAdapter {
Can you update the preceding lines, 34-38, to:

```markdown
If there is a model that does not follow the backend's typical conventions, you
can create an adapter that is specific to that model. The model-specific adapter
will override the rules in the `application` adapter.

To create a model-specific adapter, run the command `ember generate adapter <adapter-name>`.
For example, suppose there is a `post` model that needs to talk to the `v1` API
in the backend. We can run `ember generate adapter post` to create the adapter,
then specify the `post` adapter's namespace:
```

The update doesn't have to be exactly this, but I think it's a good start. If you like to suggest something else, please feel free to add a comment.

2021-04-03 08:11 UTC, ijlee2 requested changes
I think we want to keep the line `namespace='api/v1';` but make the preceding paragraph more clear about why this line is shown in the code example.

Can you have a look at my suggestion?

After we merge the pull request, I think it'd be good to backport the changes to earlier Ember versions (3.15 - 3.24).

2021-04-03 15:09 UTC, esquith commented
@ijlee2 That paragraph looks good to me. Would you like me to make the PR for Ember versions 3.15 - 3.24?

2021-04-04 06:16 UTC, ijlee2 approved these changes
Thank you for having a look at Customizing Adapters!

2021-04-04 06:16 UTC, merged