fixes typo in components -> looping-through-lists  example
ember-learn/guides-source pull request #1723
Opened 2021-08-27 20:18 UTC by lifeart

closes https://github.com/emberjs/ember.js/issues/19539

2021-08-28 18:59 UTC, locks commented
@lifeart can you backport to relevant previous versions?

2021-08-28 19:01 UTC, locks approved these changes
Thanks!

2021-08-31 11:28 UTC, ijlee2 commented on guides/release/components/looping-through-lists.md
> +};
```suggestion
}
```

2021-08-31 11:29 UTC, ijlee2 requested changes
I think `eslint` will remove the semicolon at the end of a class declaration. Before we merge the pull request, can we remove it?

2021-08-31 13:37 UTC, ijlee2 approved these changes
Thank you for helping with improving the documentation!

2021-08-31 13:39 UTC, merged