Rename `ENABLE_ALL_FEATURES` flag to `ENABLE_OPTIONAL_FEATURES` for versions v2.3.0 and up
ember-learn/guides-source pull request #1824
Opened 2022-06-18 08:39 UTC by bertdeblock

The `ENABLE_ALL_FEATURES` flag was removed in [v2.3.0](https://github.com/emberjs/ember.js/blob/5a77a4312accd672f29b48b73db2b78745335ae7/CHANGELOG.md#230-january-17-2016) in favour of `ENABLE_OPTIONAL_FEATURES`:
https://github.com/emberjs/ember.js/pull/12627

2022-06-20 16:20 UTC, locks requested changes
Since it touches quite old versions, we will have to re-compile them. I think we should do this, but I'm marking as changes requested so someone doesn't accidentally merge this and we forget to precompile the old versions.
@mansona can you provide some guidance on how to do it?

2022-08-26 18:21 UTC, bertdeblock commented
@locks Is re-compiling the older versions something we still want to do?

2022-09-07 13:59 UTC, bertdeblock commented
Can we merge this and create a separate issue for re-compiling the older versions?

2022-09-07 15:23 UTC, locks commented
sure

2022-09-07 15:23 UTC, merged